# .yamllint.yml
extends: default

rules:
  # disable the "missing document start '---'" warning entirely
  document-start: disable

  line-length:
    # allow lines up to 200 characters
    max: 200
    # only warn (won't produce a non-zero exit code)
    level: warning
