version: 2.1

# PARAMETERS: injected into pipelines and continuation orb will stitch together at runtime.
parameters:
  php_version:
    type: string
    default: "8.3"
  drupal_core_version:
    type: string
    default: "10.4"
  coding_standards_dirs:
    type: string
    default: ""
  deprecated_code_dirs:
    type: string
    default: ""
  edge_branch:
    type: string
    default: ""
  edge_build_dofdss_packages:
    type: string
    default: ""
  ssh_fingerprint:
    type: string 
    default: ""

jobs:
  build:
    parameters:
      php_version:
        type: string
      ssh_fingerprint:
        type: string
    docker:
      - image: thecodingmachine/php:<< parameters.php_version >>-v4-fpm
        environment:
          PLATFORM_REGION: "uk-1.platform.sh"
          PROJECT_ROOT: "/home/docker/project"
          PHP_EXTENSION_GD: 1
          PHP_INI_MEMORY_LIMIT: 1g
    steps:
      - checkout_code:
          ssh_fingerprint: << parameters.ssh_fingerprint >>
      - composer_tasks
      - persist_to_workspace:
          root: ./
          paths:
            - ./

  # Task to build the edge site.
  build_edge:
    parameters:
      edge_branch:
        type: string
      edge_build_dofdss_packages:
        type: string
      php_version:
        type: string
    docker:
      - image: thecodingmachine/php:<< parameters.php_version >>-v4-fpm
        environment:
          # git variables to avoid empty committer identity errors
          EMAIL: "circleci@localhost"
          GIT_COMMITTER_NAME: "Circle CI"
          GIT_AUTHOR_NAME: "Circle CI"
          EDGE_BUILD_BRANCH: << pipeline.parameters.edge_branch >>
    steps:
      - hosts_keyscan
      - checkout_code
      - install_psh_cli
      - run:
          name: Switch to edge branch
          # -b flag is important; this checkout won't have a local branch of that name
          # (although origin/$EDGE_BUILD_BRANCH does exist) so this always works and
          # lets us push -f to include everything at th end. If we use a plain checkout
          # command we miss any recent config commits and only end up bumping the
          # composer package versions after this step.
          command: git checkout -b $EDGE_BUILD_BRANCH
      - composer_tasks__edge_packages
      - run:
          name: Re-point dof-dss packages to use latest development code and push.
          command: |
            git add composer.*
            git commit -m "Set dof-dss packages to HEAD development for build"
      - run:
          name: Push changes back to GitHub
          command: |
            git push -f origin $EDGE_BUILD_BRANCH

  coding_standards:
    parameters:
      php_version:
        type: string
      coding_standards_dirs:
        type: string
    docker:
      - image: thecodingmachine/php:<< parameters.php_version >>-v4-fpm
        environment:
          PLATFORM_REGION: "uk-1.platform.sh"
          PROJECT_ROOT: "/home/docker/project"
          PHP_EXTENSION_GD: 1
          PHP_INI_MEMORY_LIMIT: 1g
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: PHPCS analysis
          command: ${PROJECT_ROOT}/phpcs.sh ${PROJECT_ROOT} << parameters.coding_standards_dirs >>

  deprecated_code:
    parameters:
      php_version:
        type: string
      deprecated_code_dirs:
        type: string
    docker:
      - image: thecodingmachine/php:<< parameters.php_version >>-v4-fpm
        environment:
          PLATFORM_REGION: "uk-1.platform.sh"
          PROJECT_ROOT: "/home/docker/project"
          PHP_EXTENSION_GD: 1
          PHP_INI_MEMORY_LIMIT: 1g
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deprecated code check
          command: cd $PROJECT_ROOT && vendor/bin/drupal-check << parameters.deprecated_code_dirs >>

commands:
  checkout_code:
    description: "Handle composer access tokens, SSH key fingerprints and code checkout"
    parameters:
      ssh_fingerprint:
        type: string
        default: ""
    steps:
      - add_ssh_keys:
          fingerprints:
            - << parameters.ssh_fingerprint >>
      - checkout

  composer_tasks:
    description: "Validate and install dependencies using composer"
    steps:
      - run:
          name: Validate composer.json and composer.lock file for consistency
          command: composer validate --no-check-all --strict
      - restore_cache:
          keys:
            - composer-vendor-{{ checksum "composer.lock" }}
      - run:
          name: Install dependencies
          command: |
            composer install --no-interaction --optimize-autoloader
      - save_cache:
          key: composer-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - ~/.composer/cache

  composer_tasks__edge_packages:
    description: "Switch dof-dss packages to HEAD on development branch"
    steps:
      - run:
          name: Switch dof-dss packages to HEAD on dev branches
          command: composer require << pipeline.parameters.edge_build_dofdss_packages >>
    
  install_psh_cli:
    description: "Install the Platform.sh CLI tool"
    steps:
      - run:
          name: Install the Platform.sh CLI tool
          command: curl -sS https://platform.sh/cli/installer | php
      - run:
          name: Add platform cli tool to $PATH
          command: echo 'export PATH="$HOME/"'.platformsh/bin':"$PATH"' >> $BASH_ENV

  hosts_keyscan:
    description: "Keyscan for hosts that require SSH access"
    steps:
      - run:
          name: Keyscan for hosts that require SSH access
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            ssh-keyscan -H ssh.$PLATFORM_REGION >> ~/.ssh/known_hosts

workflows:
  build-test:
    jobs:
      - build:
          php_version: << pipeline.parameters.php_version >>
          ssh_fingerprint: << pipeline.parameters.ssh_fingerprint >>
      - coding_standards:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          coding_standards_dirs: << pipeline.parameters.coding_standards_dirs >>
      - deprecated_code:
          requires:
            - build
          php_version: << pipeline.parameters.php_version >>
          deprecated_code_dirs: << pipeline.parameters.deprecated_code_dirs >>
  build-edge:
    triggers:
      - schedule:
          # At 04:00 every Mon-Fri
          cron: "0 4 * * 1-5"
          filters:
            branches:
              only:
                - development
    jobs:
      - build_edge:
          php_version: << pipeline.parameters.php_version >>
          edge_branch: << pipeline.parameters.edge_branch >>
          edge_build_dofdss_packages: << pipeline.parameters.edge_build_dofdss_packages >>