version: 2.1

parameters:
  php_version:
    type: string
    default: "8.3"
    description: "PHP version to use"
  
  node_version:
    type: string
    default: "18"
    description: "Node.js version to use"

executors:
  php-executor:
    docker:
      - image: cimg/php:<< parameters.php_version >>
    working_directory: ~/project

commands:
  setup-php:
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: composer install -n --prefer-dist

  setup-node:
    steps:
      - checkout
      - run:
          name: Install Node dependencies
          command: npm ci