version: 2.1

# PARAMETERS: injected into pipelines and continuation orb will stitch together at runtime.
parameters:
  php_version:
    type: string
    default: "8.3"
  drupal_core_version:
    type: string
    default: "10.4"
  coding_standards_dirs:
    type: string
    default: ""
  deprecated_code_dirs:
    type: string
    default: ""
  ssh_fingerprint:
    type: string 
    default: ""

# YAML ANCHORS: re-usable snippets of YAML.
default_docker_image: &docker_image
  docker:
    - image: thecodingmachine/php:<< parameters.php_version >>-v4-fpm
      environment:
        PLATFORM_REGION: "uk-1.platform.sh"
        PROJECT_ROOT: "/home/docker/project"
        PHP_EXTENSION_GD: 1
        PHP_INI_MEMORY_LIMIT: 1g        

# Jobs; tied in to workflows (end of file).
jobs:
  # Tests the integrity of the build, stores the results in a workspace for re-use in later jobs.
  build:
    <<: *docker_image
    steps:
      - checkout_code
      - composer_tasks
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  # Test for coding standards - will inherit the workspace/filesystem changes from build step, above.
  coding_standards:
    <<: *docker_image
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: PHPCS analysis
          command: ${PROJECT_ROOT}/phpcs.sh ${PROJECT_ROOT} << parameters.coding_standards_dirs >>

  deprecated_code:
    <<: *docker_image
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Deprecated code check
          command: cd $PROJECT_ROOT && vendor/bin/drupal-check << parameters.deprecated_code_dirs >>

# Re-usable commands.
commands:
  checkout_code:
    description: "Handle composer access tokens, SSH key fingerprints and code checkout"
    steps:
      # Add SSH user key so we can access related repositories as part of our initial clone + composer install command.
      # 65:4e >> GitHub user key fingerprint.
      - add_ssh_keys:
          fingerprints:
            - << parameters.ssh_fingerprint >>
      - checkout
  composer_tasks:
    description: "Validate and install dependencies using composer"
    steps:
      - run:
          name: Validate composer.json and composer.lock file for consistency
          command: composer validate --no-check-all --strict

      - restore_cache:
          keys:
            - composer-vendor-{{ checksum "composer.lock" }}

      - run:
          name: Install dependencies (if vendor/ missing)
          command: |
            if [ ! -d vendor ]; then
              composer install --no-interaction --optimize-autoloader
            else
              echo "Vendor directory exists, skipping install."
            fi

      - save_cache:
          key: composer-vendor-{{ checksum "composer.lock" }}
          paths:
            - vendor
            - ~/.composer/cache

# Workflow definitions.
workflows:
  build-test:
    jobs:
      - build
      - coding_standards:
          requires:
            - build
      - deprecated_code:
          requires:
            - build