version: 2.1

jobs:
  validate-config:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      # 1. Syntax check with yamllint
      - run:
          name: Install yamllint
          command: pip install --quiet yamllint
      - run:
          name: Lint shared-config.yml
          command: yamllint -c .yamllint.yml shared-config.yml
      # 2. Compose minimal config and validate with CircleCI CLI
      - run:
          name: Compose & validate CircleCI config
          command: |
            # Install CircleCI CLI
            curl -fLSs https://circle.ci/cli | sudo bash
            echo 'export PATH="$HOME/.circleci/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

            # Munge together shared-config contents with stub workflow
            cat shared-config.yml > temp_config.yml

            # Append a stub workflow that calls `build` with required args
            echo 'workflows:' >> temp_config.yml
            echo '  validate:' >> temp_config.yml
            echo '    jobs:' >> temp_config.yml
            # Use your known defaults for the parameters:
            echo '      - build: {php_version: "8.3", ssh_fingerprint: ""}' >> temp_config.yml

            # Validate the composed config
            circleci config validate -c temp_config.yml

workflows:
  build-test:
    jobs:
      - validate-config