version: 2.1

jobs:
  validate-config:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      # 1. Syntax check with yamllint
      - run:
          name: Install yamllint
          command: pip install --quiet yamllint
      - run:
          name: Lint shared-config.yml
          command: yamllint -c .yamllint shared-config.yml
      # 2. Compose minimal config and validate with CircleCI CLI
      - run:
          name: Compose & validate CircleCI config
          command: |
            # Install CircleCI CLI
            curl -fLSs https://circle.ci/cli | bash
            echo 'export PATH="$HOME/.circleci/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

            # Start our temp config with the version line
            echo 'version: 2.1' > temp_config.yml

            # Append the shared-config contents
            cat shared-config.yml >> temp_config.yml

            # Append stub workflow to mock per-repo workflows.
            echo 'workflows:' >> temp_config.yml
            echo '  validate:' >> temp_config.yml
            echo '    jobs:' >> temp_config.yml
            echo "      - $JOB_NAME" >> temp_config.yml

            # Validate the composed config
            ~/.circleci/bin/circleci config validate -c temp_config.yml

workflows:
  build-test:
    jobs:
      - validate-config
